"""create_model_registry_table

Revision ID: 36ddcb12db54
Revises: 86c4658336f6
Create Date: 2025-12-06 22:48:25.643622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36ddcb12db54'
down_revision: Union[str, Sequence[str], None] = '86c4658336f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('git_sha', sa.String(), nullable=True),
    sa.Column('train_start_date', sa.DateTime(), nullable=True),
    sa.Column('train_end_date', sa.DateTime(), nullable=True),
    sa.Column('primary_metric', sa.String(), nullable=True),
    sa.Column('metrics_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_production', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_id'), 'models', ['id'], unique=False)
    op.create_index(op.f('ix_models_name'), 'models', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_models_name'), table_name='models')
    op.drop_index(op.f('ix_models_id'), table_name='models')
    op.drop_table('models')
    # ### end Alembic commands ###
