"""Create raw_series table

Revision ID: 86c4658336f6
Revises: 
Create Date: 2025-10-05 17:41:14.645326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86c4658336f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_series_id'), 'raw_series', ['id'], unique=False)
    op.create_index(op.f('ix_raw_series_series_id'), 'raw_series', ['series_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_series_series_id'), table_name='raw_series')
    op.drop_index(op.f('ix_raw_series_id'), table_name='raw_series')
    op.drop_table('raw_series')
    # ### end Alembic commands ###
